package com.example.pro.ai

enum class AiIntent {
    GENERAL_SUMMARY,
    SPENDING_ANALYSIS,
    CATEGORY_ANALYSIS,
    BUDGET_ANALYSIS,
    SAVINGS_ANALYSIS,
    RECURRING_ANALYSIS,
    FORECAST_QUERY,
    WHAT_IF_QUERY,
    COMPARISON_QUERY,
    TRANSACTION_LOOKUP,
    UNSUPPORTED
}
